"""
API Routes for Simulated Payment Rail Network Health.
"""

from typing import Dict, Any, List, Optional
from fastapi import APIRouter, Query
from pydantic import BaseModel

from app.models.enums import NetworkScenario
from app.models.schemas import RailHealthTelemetry
from app.engine.network_health import SimulatedNetworkHealthEngine, SCENARIO_PRESETS, RAIL_METADATA

router = APIRouter(prefix="/api/network", tags=["Simulated Network Health"])

class SimulateNetworkRequest(BaseModel):
    scenario: NetworkScenario = NetworkScenario.SBI_DEGRADED
    seed: int = 42
    target_rail: Optional[str] = "UPI_SBI"

@router.get("/health")
def get_network_health(
    scenario: NetworkScenario = Query(default=NetworkScenario.SBI_DEGRADED),
    seed: int = Query(default=42),
):
    """Returns simulated health telemetry for all payment rails under the requested scenario and seed."""
    rails = SimulatedNetworkHealthEngine.get_all_rail_health(scenario=scenario, seed=seed)
    return {
        "scenario": scenario.value,
        "seed": seed,
        "rails": {k: v.model_dump() for k, v in rails.items()},
        "disclaimer": "SIMULATED NETWORK HEALTH: Generated by deterministic scenario simulator; not live bank telemetry.",
    }

@router.post("/simulate")
def simulate_network(req: SimulateNetworkRequest):
    """Simulates network condition change, returning telemetry and temporal timeline."""
    rails = SimulatedNetworkHealthEngine.get_all_rail_health(scenario=req.scenario, seed=req.seed)
    timeline = SimulatedNetworkHealthEngine.get_temporal_timeline(
        rail_id=req.target_rail or "UPI_SBI",
        scenario=req.scenario,
        seed=req.seed,
    )
    return {
        "scenario": req.scenario.value,
        "seed": req.seed,
        "rails": {k: v.model_dump() for k, v in rails.items()},
        "timeline": timeline,
        "disclaimer": "SIMULATED NETWORK HEALTH: Generated by deterministic scenario simulator; not live bank telemetry.",
    }

@router.get("/scenarios")
def list_scenarios():
    """Lists all available deterministic network simulation scenarios."""
    return [
        {
            "id": s.value,
            "label": s.value.replace("_", " ").title(),
            "description": f"Preset for {s.value} telemetry patterns.",
        }
        for s in NetworkScenario
    ]

@router.get("/timeline")
def get_timeline(
    rail_id: str = Query(default="UPI_SBI"),
    scenario: NetworkScenario = Query(default=NetworkScenario.SBI_DEGRADED),
    seed: int = Query(default=42),
):
    """Returns 7-step temporal telemetry timeline showing degradation and recovery."""
    return SimulatedNetworkHealthEngine.get_temporal_timeline(
        rail_id=rail_id,
        scenario=scenario,
        seed=seed,
    )
